/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\public\background.glb --transform 
Files: .\public\background.glb [22.37MB] > C:\workspace\jjc\background-transformed.glb [1.74MB] (92%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/background-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.input.geometry} material={materials.material_0} rotation={[Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/background-transformed.glb')
